server:
  port: 8001


spring:
  application:
    name: micro-server01
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.226.39:8848

#暴露监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

